# ── Ansible Inventory ──────────────────────────────────────────────────────
# Replace YOUR_EC2_PUBLIC_IP with your actual EC2 Elastic IP
# obtained from: terraform output public_ip
# ─────────────────────────────────────────────────────────────────────────

[flask_servers]
flask-prod  ansible_host=YOUR_EC2_PUBLIC_IP

[flask_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/your-key.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
